### ISSUE TITLE
Cannot invoke "java.nio.file.WatchService.close()" because "this.watcher" is null

### ISSUE THREAD

**Issue by NotAlexNoyle** [LapisPlugins/AFKPlus#45] opened 2022-06-09 00:24 UTC
[20:22:24 INFO]: [AFKPlus] Disabling AFKPlus v3.3.14
[20:22:24 ERROR]: Error occurred while disabling AFKPlus v3.3.14 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.nio.file.WatchService.close()" because "this.watcher" is null
        at net.lapismc.afkplus.util.core.utils.LapisCoreFileWatcher.stop(LapisCoreFileWatcher.java:72) ~[AFKPlus.jar:?]
        at net.lapismc.afkplus.AFKPlus.onDisable(AFKPlus.java:72) ~[AFKPlus.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:555) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:494) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:984) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:842) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

This error occurs every server restart. I am using purpur 1.18.2.

**Comment by Dart2112** [comment] 2022-06-11 03:32
Interesting, that definitely shouldn't be happening. Any errors on startup?

**Comment by NotAlexNoyle** [comment] 2022-06-11 05:31
> Interesting, that definitely shouldn't be happening. Any errors on startup?

No errors on startup.

**Comment by Dart2112** [comment] 2022-06-11 05:57
For that error to occor you should have a message like this in when the plugin enables

AFKPlus file watcher has stopped, configs wont be reloaded until the server restarts

**Comment by NotAlexNoyle** [comment] 2022-06-18 06:20
I do see that 

> [02:10:35 WARN]: [AFKPlus] AFKPlus file watcher has stopped, configs wont be reloaded until the server restarts

**Comment by Dart2112** [comment] 2022-06-18 06:38
I've attached a jar file (it's in a zip archive since I can't attach raw .jar files), try using it in place of your current AFKPlus install

The only difference is that it will print out the error in the console underneath that warning that you've got there

Hopefully that error should let me know whats going wrong here

[AFKPlus-3.3.14.zip](https://github.com/LapisPlugins/AFKPlus/files/8933073/AFKPlus-3.3.14.zip)

**Comment by NotAlexNoyle** [comment] 2022-06-21 06:33
```
[02:31:49 WARN]: [AFKPlus] AFKPlus file watcher has stopped, configs wont be reloaded until the server restarts
[02:31:49 WARN]: java.io.IOException: Function not implemented
[02:31:49 WARN]:        at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62)
[02:31:49 WARN]:        at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[02:31:49 WARN]:        at AFKPlus-3.3.14.jar//net.lapismc.afkplus.util.core.utils.LapisCoreFileWatcher.watcher(LapisCoreFileWatcher.java:79)
[02:31:49 WARN]:        at AFKPlus-3.3.14.jar//net.lapismc.afkplus.util.core.utils.LapisCoreFileWatcher.lambda$start$0(LapisCoreFileWatcher.java:53)
[02:31:49 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[02:31:49 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:31:49 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:31:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:31:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:31:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Dart2112** [comment] 2022-06-21 12:07
Its an issue with either your OS or the JRE

I'm calling this code

`FileSystems.getDefault().newWatchService();`

and the system's response is 

`java.io.IOException: Function not implemented`

I have found people who have had this issue on Macs running on M1 chips, so that may be the cause. Otherwise, the error points to a Linux system

It's working for me on Linux using OpenJRE/OpenJDK, so if you have system admin or can choose which JRE to use I would suggest trying that

**Comment by NotAlexNoyle** [comment] 2022-06-21 20:51
I’m not running Linux, I’m running FreeBSD.

I believe this is a Linux specific call:

`at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62)
[02:31:49 WARN]:        at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47) `

That might also explain why it’s not working on M1 Macs.

**Comment by Dart2112** [comment] 2022-06-22 05:32
@NotAlexNoyle the thing is that I'm not the one making that Linux call. That's your java install doing that. It works fine on windows and Linux but apparently not FreeBSD, I'll look into it some more but I suspect it's a problem with your JRE attempting a Linux call when it's not installed on Linux

What JRE are you using?

**Comment by NotAlexNoyle** [comment] 2022-06-22 05:52
> I suspect it's a problem with your JRE attempting a Linux call when it's not installed on Linux

This is almost certainly what is happening here. I am using GraalVM Community Edition 22.1. It's running in the Linuxulator.

I believe the root of the problem is that both FreeBSD and MacOS are missing this:

`watcher = FileSystems.getDefault().newWatchService();`

So the problem is really in https://github.com/LapisPlugins/LapisCore/blob/e224461b241b523bf94f7e35f6c9de106bde2987/src/main/java/net/lapismc/lapiscore/utils/LapisCoreFileWatcher.java not AFKPlus itself.

**Comment by Dart2112** [comment] 2022-06-22 06:12
> > I suspect it's a problem with your JRE attempting a Linux call when it's not installed on Linux
> 
> This is almost certainly what is happening here. I am using GraalVM Community Edition 22.1. It's running in the Linuxulator.
> 
> I believe the root of the problem is that both FreeBSD and MacOS are missing this:
> 
> `watcher = FileSystems.getDefault().newWatchService();`
> 
> So the problem is really in https://github.com/LapisPlugins/LapisCore/blob/e224461b241b523bf94f7e35f6c9de106bde2987/src/main/java/net/lapismc/lapiscore/utils/LapisCoreFileWatcher.java not AFKPlus itself.

The error on shutdown still shouldn't happen. That I can fix, what I can't fix is the file watching. I'll push out an update to LapisCore and AFKPlus in the next couple of days to rectify that

**Comment by NotAlexNoyle** [comment] 2022-06-22 07:01
Thanks. I'll eagerly await your update. Perhaps after it is pushed, I can try to make LapisCoreFileWatcher more platform agnostic for you.

**Comment by Dart2112** [comment] 2022-06-26 17:03
I'm gonna close this issue since the bug has been fixed. But I have opened one in LapisCore to make the file watcher platform agnostic

See the mention above

**Closed by Dart2112** 2022-06-26 17:03 UTC
