### ISSUE TITLE
[bug] ActionPlayerRequirement not working

### ISSUE THREAD

**Issue by Uboaaaaa** [LapisPlugins/AFKPlus#31] opened 2021-06-03 19:21 UTC
**Description:**
`ActionPlayerRequirement: 11`, server has 8 players online. The action still get executed and kicked the afk player.

**Plugin version:** 3.3.2
**Minecraft version:** 1.16.5
**Server version:** git-Yatopia-ver/1.16.5-117 (Will do more testing on an upstream)

**Additional information:** 
Essentials installed. `auto-afk-kick` and `auto-afk:` are both set to `-1`.

The permission the player has:
https://paste.gg/p/anonymous/fc3a1581b47a41d59a4a7a41bbe29b65

**Comment by Uboaaaaa** [comment] 2021-06-03 21:03
Reproduced on paper.

**Server version:** git-Paper-762 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Console log and configuration:** https://paste.gg/p/anonymous/6fa13eb448434edbba1e220f509a1906

**Comment by Dart2112** [comment] 2021-06-25 04:32
Turns out it was caused by a simple backwards if statement. This has been fixed on Git and will be in the next update. If you want it now you can compile it from here

**Closed** 2021-07-20 03:33 UTC
